version: "3.9"

# Postgres credentials
x-database-credentials: &database-credentials
  DATABASE_USER: ${DATABASE_USER:-postgres}
  DATABASE_PASSWORD: ${DATABASE_PASSWORD:-password}

# ClickHouse credentials
x-clickhouse-credentials: &clickhouse-credentials
  CLICKHOUSE_USER: ${CLICKHOUSE_USER:-dittofeed}
  CLICKHOUSE_PASSWORD: ${CLICKHOUSE_PASSWORD:-password}

# Environment variables for backend apps
x-backend-app-env: &backend-app-env
  <<: [*clickhouse-credentials, *database-credentials]
  NODE_ENV: production
  DATABASE_HOST: ${DATABASE_HOST}
  DATABASE_PORT: ${DATABASE_PORT:-5432}
  CLICKHOUSE_HOST: ${CLICKHOUSE_HOST}
  CLICKHOUSE_PORT: ${CLICKHOUSE_PORT:-8123}
  TEMPORAL_ADDRESS: ${TEMPORAL_ADDRESS:-temporal:7233}

services:
  dashboard:
    image: dittofeed/dittofeed-dashboard:${IMAGE_TAG:-v0.17.0}
    platform: linux/amd64
    ports:
      - "3000:3000"
    restart: always
    depends_on:
      - temporal
      - api
    env_file:
      - .env
    environment:
      <<: *backend-app-env
    networks:
      - dittofeed-network

  api:
    image: dittofeed/dittofeed-api:${IMAGE_TAG:-v0.17.0}
    restart: always
    platform: linux/amd64
    ports:
      - "3001:3001"
    depends_on:
      - temporal
      - worker
    env_file:
      - .env
    environment:
      <<: *backend-app-env
    networks:
      - dittofeed-network

  worker:
    image: dittofeed/dittofeed-worker:${IMAGE_TAG:-v0.17.0}
    restart: always
    depends_on:
      - temporal
    env_file:
      - .env
    environment:
      <<: *backend-app-env
    networks:
      - dittofeed-network

  admin-cli:
    image: dittofeed/dittofeed-admin-cli:${IMAGE_TAG:-v0.17.0}
    entrypoint: []
    platform: linux/amd64
    command: tail -f /dev/null
    tty: true
    env_file:
      - .env
    depends_on:
      - temporal
    environment:
      PRETTY_LOGS: true
      <<: *backend-app-env
    networks:
      - dittofeed-network

  temporal:
    container_name: temporal
    environment:
      - DB=postgresql
      - DB_PORT=${DATABASE_PORT:-5432}
      - POSTGRES_USER=${DATABASE_USER:-postgres}
      - POSTGRES_PWD=${DATABASE_PASSWORD:-password}
      - POSTGRES_SEEDS=${DATABASE_HOST}
      - DYNAMIC_CONFIG_FILE_PATH=config/dynamicconfig/prod.yaml
    image: temporalio/auto-setup:${TEMPORAL_VERSION:-1.18.5}
    labels:
      kompose.volume.type: configMap
    networks:
      - dittofeed-network
    ports:
      - 7233:7233
    volumes:
      - ./packages/backend-lib/temporal-dynamicconfig:/etc/temporal/config/dynamicconfig

volumes:
  clickhouse_lib:
  clickhouse_log:

networks:
  dittofeed-network:
    driver: bridge
    name: dittofeed-network